[TNL-5941] Adding pagination support
shahbazn/edx-val pull request #1
Opened 2017-02-13 05:23 UTC by shahbazn

## [TNL-5941](https://openedx.atlassian.net/browse/TNL-5941)

### Description

Adding paginations support for list videos API

### Sandbox
- [ ] Build a sandbox for your branch and add a link here

### Testing
- [ ] i18n
- [ ] RTL
- [ ] safecommit violation code review process
- [ ] Unit, integration, acceptance tests as appropriate
- [ ] Analytics
- [ ] Performance
- [ ] Database migrations are backwards-compatible

### Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [ ] Code review: @muhammad-ammar
- [ ] Code review: @mushtaqak
- [ ] Doc Review: @...
- [ ] UX review: @...
- [ ] Accessibility review: @...
- [ ] Product review: @...

### Devops assistance
If it's needed, or even if you suspect it might be needed, do any/all these things as early as possible. Don't surprise devops right before merging!
For example, touching envs/aws.py or or envs/common.py are dead giveaways that you'll need assistance when pushing your changes out.
Things that require devops attention include, but are not limited to:
- configuration changes
- feature flags
- migrations
Ways to get devops attention, pick-and-choose whichever is most appropriate for your specific PR:
- [ ] Mention your concerns to Max in standup, or any other member of devops face-to-face when convinient
- [ ] Tag devops on your PR (@ edx/devops, or @ maxrothman), either for review (more specific to devops = better) or just a general FYI
- [ ] File a support ticket by emailing support@edx.org

FYI: Tag anyone who might be interested in this PR here.

### Post-review
- [ ] Rebase and squash commits

2017-02-16 08:38 UTC, muzaffaryousaf commented on edxval/api.py
> +        "page_size": page_size,
I'd recommend using DRF based serialized data. Can't you get serialized data by using some DRF serializer class ?

2017-02-16 09:27 UTC, muzaffaryousaf commented on edxval/api.py
> +    page_no = int(kwargs.pop("page", 1))
The pagination should be optional based on the given parameter, to make sure that we won't break any other calls to this method.

2017-02-17 05:49 UTC, shahbazn commented on edxval/api.py
> +        "page_size": page_size,
+1 will update

2017-02-17 06:02 UTC, muzaffaryousaf requested changes
@shahbazn I've left some comments, let me know when you're done with addressing them.

2017-02-17 06:02 UTC, muzaffaryousaf commented on edxval/api.py
> +    videos_qs = Video.objects.filter(**video_filter)
I'd leave the name `videos` as it or won't use `qs` at-least.

2017-02-17 06:02 UTC, muzaffaryousaf commented on edxval/tests/test_api.py
> +        videos = list(api.get_videos_for_course('other-course')["videos"])
I'd like to see complete test coverage for paginated data.

2017-02-17 06:02 UTC, muzaffaryousaf commented on edxval/tests/test_api.py
> +        videos = list(api.get_videos_for_course('other-course')["videos"])
To get an rough idea, you can look at notes api test cases.

2017-02-17 06:02 UTC, muzaffaryousaf commented on edxval/tests/test_api.py
> +            actual_videos = api_func(list(reversed(expected_ids)), sort_field, sort_direction)["videos"]
I'll leave these tests as it and add optional pagination parameter to apply paging and test it through new test cases.

2017-02-17 06:02 UTC, muzaffaryousaf commented on edxval/api.py
> -            videos = videos.reverse()
I'll write a test that'll make sure that videos are reverse and paginated as expected.

2017-02-27 12:55 UTC, muzaffaryousaf commented on edxval/api.py
> +        page_size = int(kwargs.pop("page_size", 20))
Default page size should come from settings.

2017-02-28 10:06 UTC, shahbazn commented on edxval/api.py
> +    videos_qs = Video.objects.filter(**video_filter)
its a query set thats why the name to keep it separate from videos below which has the list of videos

2017-02-28 11:16 UTC, muzaffaryousaf commented on edxval/serializers.py
> +            'results': data
```
We use the conventions established by DRF, with some extra fields:
next: A URL to the next page, or null.
previous: A URL to the previous page, or null.
count: The total number of items.
num_pages: The total number of pages.
results: List of results.
The query parameters are as follows:
page - the page of results (zero indexed)
page_size - the number of results to return per page
sort_order - a string indicating the desired order (no direction modifiers)
```

2017-02-28 11:26 UTC, shahbazn commented on edxval/serializers.py
> +            'results': data
this is using only the fields required by pagination header/footer on the front end side. for example next and previous page links would be redundant if added.

2017-02-28 11:27 UTC, shahbazn commented on edxval/api.py
> -            videos = videos.reverse()
added

2017-02-28 11:42 UTC, muzaffaryousaf commented on edxval/serializers.py
> +            'results': data
and how about other fields total_count, total_pages and current_page ?

2017-02-28 11:48 UTC, shahbazn commented on edxval/serializers.py
> +            'results': data
total_count used by paging header. total_pages and current_page used by paging footer

2017-02-28 11:54 UTC, muzaffaryousaf commented
### Sandbox link --> https://studio-video-paging.sandbox.edx.org/videos/course-v1:edX+DemoX+Demo_Course

2017-02-28 12:50 UTC, muzaffaryousaf commented on edxval/api.py
> +        page_size = int(kwargs.pop("page_size", 20))
Also, i would set the page size to 100 for now.

2017-02-28 13:46 UTC, muzaffaryousaf commented on edxval/api.py
> +        page_size = int(kwargs.pop("page_size", 20))
but do it at very end of the all of this work.

2017-03-01 13:48 UTC, muzaffaryousaf commented on edxval/serializers.py
> +        return list(self.page)
Why do we need to override `paginate_queryset` method given that we're not doing anything different than the actual method.

2017-03-01 13:49 UTC, muzaffaryousaf commented on edxval/serializers.py
> +            'results': data
Why redundant fields, i'm not able to see them in response.

2017-03-01 13:56 UTC, muzaffaryousaf commented on edxval/serializers.py
> +            'results': data
Would't be a class like this is enough for edx-val https://github.com/edx/edx-platform/blob/master/openedx/core/lib/api/paginators.py#L10

2017-03-03 07:25 UTC, shahbazn commented on edxval/serializers.py
> +        return list(self.page)
we are. original method requires request object. cannot be used as is.

2017-03-03 11:22 UTC, shahbazn commented on edxval/serializers.py
> +            'results': data
done

2017-03-03 11:30 UTC, shahbazn commented on edxval/api.py
> +        page_size = int(kwargs.pop("page_size", 20))
done

2017-03-03 11:31 UTC, shahbazn commented on edxval/serializers.py
> +        return list(self.page)
original method requires a request object. and will fail if used as is

2017-03-07 12:10 UTC, closed without merging